"""make people title and email not null

Revision ID: 0e8cfe9fa7db
Revises: d9833c516979
Create Date: 2026-04-03 00:05:08.503374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e8cfe9fa7db'
down_revision: Union[str, Sequence[str], None] = 'd9833c516979'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('people', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('people', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('people', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('people', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
